# Generated by Django 3.0 on 2022-07-05 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parallel',
            fields=[
                ('number', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False, verbose_name='Параллель')),
            ],
            options={
                'verbose_name': 'Параллель',
                'verbose_name_plural': 'Параллели',
            },
        ),
        migrations.CreateModel(
            name='SchoolSubject',
            fields=[
                ('subject', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Предмет')),
                ('result_date', models.DateField(blank=True, null=True, verbose_name='Результат ожидается')),
                ('start_parallel', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Доступна с класса')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('clsroom', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Класс')),
                ('parallel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parallel_num', to='main_site.Parallel', verbose_name='Параллель')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
    ]
