# Generated by Django 3.0 on 2022-07-05 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='parallel',
        ),
    ]
