# Generated by Django 3.0 on 2022-07-21 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_remove_group_parallel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolsubject',
            options={'ordering': ['subject'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
    ]
