# Generated by Django 3.0 on 2022-07-05 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_remove_group_parallel'),
        ('users', '0002_auto_20220706_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_member', to='main_site.Group', verbose_name='Класс'),
        ),
    ]
