# Generated by Django 3.0 on 2022-07-21 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220715_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='registered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pupil_db_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='registered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_db_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
