# Generated by Django 3.0 on 2022-07-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220721_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='registered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='registered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
