# Generated by Django 3.0 on 2022-07-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0002_auto_20220705_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='pupil',
        ),
        migrations.AddField(
            model_name='code',
            name='issued',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Код выдан'),
        ),
    ]
