# Generated by Django 3.0 on 2022-07-16 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0003_auto_20220706_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedcodes',
            name='code',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_code', to='codes.Code', verbose_name='Выданный код'),
        ),
    ]
