# Generated by Django 3.0 on 2022-07-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0004_auto_20220717_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedcodes',
            name='result_date',
        ),
        migrations.RemoveField(
            model_name='issuedcodes',
            name='subject',
        ),
    ]
