# Generated by Django 3.0 on 2022-07-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0006_auto_20220717_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedcodes',
            name='pupil',
            field=models.CharField(max_length=100, verbose_name='Кому выдан'),
        ),
    ]
