# Generated by Django 3.0 on 2022-07-18 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220715_1512'),
        ('codes', '0007_auto_20220718_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='issued',
        ),
        migrations.AddField(
            model_name='code',
            name='issue_date',
            field=models.DateField(null=True, verbose_name='Время выдачи'),
        ),
        migrations.AddField(
            model_name='code',
            name='issued_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_code', to='users.Pupil', verbose_name='Выдан'),
        ),
        migrations.AddField(
            model_name='code',
            name='max_result',
            field=models.CharField(max_length=4, null=True, verbose_name='Максимум баллов'),
        ),
        migrations.AddField(
            model_name='code',
            name='result',
            field=models.CharField(max_length=100, null=True, verbose_name='Результат'),
        ),
    ]
