# Generated by Django 3.0 on 2022-07-20 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codes', '0008_auto_20220718_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='issued_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_code', to=settings.AUTH_USER_MODEL, verbose_name='Выдан'),
        ),
    ]
